# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/373e6339-e2dd-4f29-b6aa-c54382dd580d";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/43D6-1BE0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/373e6339-e2dd-4f29-b6aa-c54382dd580d";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/373e6339-e2dd-4f29-b6aa-c54382dd580d";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f367ffe1-b0b6-4fff-920a-469584e9cd42"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
