#!/bin/sh

. ~/scripts/tofi/config

entry=$(printf "power-saver\nbalanced\nperformance" | tofi_full "mode")
entry=$(echo $entry | cut -d' ' -f2 )

notify-send "Power Mode" "Setting mode to $entry"
pkexec powerprofilesctl set $entry
